#!/bin/bash

############################
# Ahmad Beyh | NatBrainLab #
# Version 20201124         #
############################

usage() {
cat << EOF

usage:
  $(basename $0) <bvec_file> [logical]

Checks whether a bvec samples the full sphere or not
by calculating the mean vector along each axis. If the
mean along any axis has an amplitude larger than 0.2,
then the bvec is NOT sampled on a full sphere.

Use the logical option to obtain a 0/1 verdict (1=full).

Examples:
  $(basename $0) data.bvec
  $(basename $0) data.bvec 1

EOF
exit 1
}

[ $# -lt 1 -o $# -gt 2 ] && usage

logicalAnswer=0
if [ $# -eq 2 ]; then
  if [ $2 == "1" ]; then
    logicalAnswer=1
  fi
fi

thr=0.2 # this is the threshold used.
bvec=$(cd $(dirname $1) && pwd)/$(basename $1)

if [ $(cat $bvec | wc -l) -gt 3 ]; then
  echo
  echo "$(basename $0): ERROR: bvec file '${bvec}' not 3xN."
  echo
  exit 1
fi

avgs=($(cat $bvec | awk '{sum=0; n=0; for(i=1;i<=NF;i++) {sum+=$i; ++n} printf "%0.5f\n", sum/n}'))
x=${avgs[0]}
y=${avgs[1]}
z=${avgs[2]}

abs_x=$(echo $x | awk '{if($1<0) {printf "%0.5f\n", $1*-1} else {printf "%0.5f\n", $1}}')
abs_y=$(echo $y | awk '{if($1<0) {printf "%0.5f\n", $1*-1} else {printf "%0.5f\n", $1}}')
abs_z=$(echo $z | awk '{if($1<0) {printf "%0.5f\n", $1*-1} else {printf "%0.5f\n", $1}}')

if (( $(echo "$abs_x > $thr" | bc) )) || (( $(echo "$abs_y > $thr" | bc) )) || (( $(echo "$abs_z > $thr" | bc) )); then
    if [ $logicalAnswer -eq 0 ]; then
        echo
        echo " >>> The data is ***NOT*** sampled on a full sphere."
        echo " >>> Average b-vector: [${avgs[0]}; ${avgs[1]}; ${avgs[2]}]"
        echo
    else
        echo 0
    fi
else
    if [ $logicalAnswer -eq 0 ]; then
        echo
        echo " >>> The data is sampled on a full sphere."
        echo " >>> Average b-vector: [${avgs[0]}; ${avgs[1]}; ${avgs[2]}]"
        echo
    else
        echo 1
    fi
fi
